# Setup
title:            AI in Production
tagline:          'KI 2024 Workshop - AI in Production'
description:      'An info page for the Workshop held at <a href="https://www.informatik.uni-wuerzburg.de/ki24/" target="_blank">KI 2024 - 47th German Conference on Artificial Intelligence</a>. Hosted by <a href="www.htw-dresden.de" target="_blank">@HTWD</a>.'
url:              https://krockema.github.io/AIP-2024
baseurl:          ''
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      toc: true

# About and contact
author:
  name:           'Martin Krockert'
  email:          martin.krockert@htw-dresden.de
  url:            https://github.com/Krockema

toc:
  min_level: 1
  max_level: 2
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-toc

# Custom vars
version:          0.0.1

include:
 - _pages
 - _posts
